### ISSUE TITLE
ServiceLocatorAwareInterface Problem

### ISSUE THREAD

**Issue by kokspflanze** [samsonasik/SanCaptcha#8]
hi,

i saw some errors in the module about the ServiceLocatorAwareInterface with the latest zend-mvc version (2.7.3).

I think about the fix and i saw some possible changes, like add the require-list in the composer.json, switch to min php 5.5 and maybe move to middleware.
But before i do that or someone else it would be better to create a release version, so everyone else with a older system can use it with php 5.3 and for version 2 we add the new features.

What you think about it?

**Comment by samsonasik** [comment]
@kokspflanze fixed the zend-mvc ~2.7.3 support, release created https://github.com/samsonasik/SanCaptcha/releases/tag/0.0.1 . For middleware support or other features, I open for Pull Request ;)

Thank you ;)

**Comment by samsonasik** [comment]
beside the zend-mvc ~2.7.3 support, just tagged new 0.0.2 as suffix issue fix, please tests:
```
 composer require san/san-captcha:0.*
```
